baseURL = "https://www.itsnikhil.codes/"
copyright = "ItsNikhil"
disqusShortname = "itsnikhil"
googleAnalytics = "UA-119427755-1"
languageCode = "en-us"
theme = "hugo-theme-cactus"
title = "ItsNikhil"
[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.83.1"
[context.production.environment]
HUGO_VERSION = "0.83.1"
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3
[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
colortheme = "white"
dateFormat = "2006-01-02"
description = "I am a programmer interested in all sorts of technology. I like working on open source projects, writing blog articles, and reading on the internet. I also like swimming, biking and playing games. I study at The Northcap University."
googleAnalyticsAsync = true
mainSection = "posts"
postsOnHomePage = 5
projectsUrl = "https://github.com/gohugoio"
rss = true
showAllPostsOnHomePage = false
showProjectsList = true
show_updated = false
tagsOverview = true
[params.comments]
enabled = true
engine = "disqus"
[[params.social]]
link = "https://github.com/itsnikhil"
name = "github"
[[params.social]]
link = "https://linkedin.com/in/taneja03"
name = "linkedin"
[[params.social]]
link = "taneja.nikhil03@gmail.com"
name = "email"
